### ISSUE TITLE
Using openssl 1.1.1 or vendored in the openssl crate causes "Unable to detect openssl version"

### ISSUE THREAD

**Issue by indykish** [stepancheg/rust-tls-api#28]
Hello

We are migrating to `**openssl 0.10**`, `**vendored**` (to be on the latest level of openssl) that works in different distros our dev guys use. 

I see from the https://github.com/stepancheg/rust-tls-api/blob/master/impl-openssl/build.rs
there is an explicit  lock on the versions. 

So  tls-api-openssl supports upto `**1.1.0**` as see in the `**build.rs**` file.

The vendored version is `**1.1.1**`

Is is safe to change [build.rs](https://github.com/stepancheg/rust-tls-api/blob/master/impl-openssl/build.rs) by adding a `**switch for 111*``  as well.

as below:

```rust
fn main() {
    // HAS
    match env::var("DEP_OPENSSL_VERSION") {
        Ok(ref v) if v == "101" => {
        }
        Ok(ref v) if v == "102" => {
            println!("cargo:rustc-cfg=has_alpn");
        }
        Ok(ref v) if v == "110" => {
            println!("cargo:rustc-cfg=has_alpn");
        }
        Ok(ref v) if v == "111" => {
            println!("cargo:rustc-cfg=has_alpn");
        }
        _ => panic!("Unable to detect OpenSSL version"),
    }
}
) 
```

Are there reasons that  **111** isn't supported yet ? 

I am on Arch, so it uses 1.1.1, but want to use the vendored feature in openssl crate.

**Comment by indykish** [comment]
Well let me try and test.

**Comment by indykish** [comment]
Yeah,  that is working good.

**Before**
![Screenshot from 2019-07-18 21-09-37](https://user-images.githubusercontent.com/1402479/61471591-a20af780-a9a0-11e9-8bb3-8d519190e9dd.png)


From the forked copy in [indykish/rust-tls-api](https://github.com/indykish/rust-tls-api)
![Screenshot from 2019-07-18 21-11-08](https://user-images.githubusercontent.com/1402479/61471607-a6cfab80-a9a0-11e9-9cac-f78816507914.png)

**Comment by indykish** [comment]
Here is the [diff](https://github.com/indykish/rust-tls-api/commit/e891a37494293415913be80fe7deb9501b4fcf04)

**Comment by indykish** [comment]
I support there shouldn't be any impact using openssl 1.1.1. So looking forward to hearing your views @stepancheg  

Thanks.

**Comment by indykish** [comment]
Thats a simple change, hopefully you add it in **0.3.0**

**Comment by stepancheg** [comment]
Looks right. Can you open PR please?

**Comment by indykish** [comment]
Ok thanks. will do.
