### ISSUE TITLE
Lift Sync restriction on accepted streams

### ISSUE THREAD

**Issue by algesten** [stepancheg/rust-tls-api#32]
The type signature of `accept()` requires me to provide a stream that is `Sync`. This seems overly restrictive to me. On a theoretical level, how do I even construct a stream that is sync? 

```rust
   fn accept<'a, S>(
        &'a self,
        stream: S,
    ) -> Pin<Box<dyn Future<Output = Result<TlsStream<S>>> + Send + 'a>>
    where
        S: AsyncRead + AsyncWrite + fmt::Debug + Unpin + Send + Sync + 'static;
```

**Comment by stepancheg** [comment]
Probably `Send` should be enough. Not sure, need to try, and you are welcome to try.

Out of curiosity, why your stream is not `Sync`?

**Comment by algesten** [comment]
Good point! For some reason in my mind types that are `Sync` are mostly like super simple `Copy` style types. But investigating it further, I seem to got it wrong. I've read the nomicon like 5 times today and still don't _quite_ get why something that is `Send` isn't always `Sync` :)

**Comment by algesten** [comment]
Feel free to close this issue.
