### ISSUE TITLE
Option to disable server certificate authentication

### ISSUE THREAD

**Issue by cecton** [stepancheg/rust-tls-api#35]
I'm making [a small CLI to control a Roomba](https://github.com/cecton/roomba-s9plus-cli) and I need to send a specific network packet using TLS ([see here the code I'm trying to clone from JS](https://github.com/koalazak/dorita980/blob/master/bin/getpassword.js#L84-L111)).

Unfortunately I always get the error:
> Error: Custom { kind: Other, error: Failure(MidHandshakeSslStream { stream: SslStream { stream: AsyncIoAsSyncIo { inner: TcpStream { addr: V4(10.10.0.238:49792), peer: V4(10.10.0.90:8883), fd: 6 }, context: 0x7ffdc6b7e6e0 }, ssl: Ssl { state: "error", verify_result: X509VerifyResult { code: 20, error: "unable to get local issuer certificate" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1913 }]))) } }) }

Because I think it is still verifying the certificate even if I don't verify the hostname? Here is the code:

```rust
#[tokio::main]
async fn sign_up<A: ToSocketAddrs + std::fmt::Display>(addr: A) -> std::io::Result<()> {
    let packet: &[u8] = &[0xf0, 0x05, 0xef, 0xcc, 0x3b, 29, 00];

    let tcp_stream = TcpStream::connect(addr).await?;

    let mut builder = tls_api_openssl::TlsConnector::builder().expect("builder");
    builder.set_verify_hostname(false)?;
    let connector = builder.build().expect("build");
    let mut tls_stream: TlsStream<_> = connector.connect("ignore", tcp_stream).await?;

    println!("handshake complete");

    tls_stream.write_all(packet).await?;
    let mut result = vec![];
    tls_stream.read_to_end(&mut result).await?;

    println!("{}", String::from_utf8_lossy(&result));

    Ok(())
}
```

I also used paho for this project and there is a difference between checking the hostname and disabling the server certificate authentication. It works when I do [`.enable_server_cert_auth(false)`](https://github.com/cecton/roomba-s9plus-cli/blob/master/src/main.rs#L31) but it won't work if I just disable the verification mechanism: [`.verify(false)`](https://github.com/eclipse/paho.mqtt.rust/blob/master/src/ssl_options.rs#L260) (not in the doc because the option is available for next release).

I couldn't find an equivalent in tls-api. Is it a missing feature or do I miss something?

Thanks

**Comment by stepancheg** [comment]
Hello! I think it's not possible to set it directly using tls-api.

However, it is possible to access openssl builder from tls-api builder.

Your example can be modified to include a line:

```
builder.builder.set_verify(SslVerifyMode::NONE);
// builder.builder is openssl::ssl::SslConnectorBuilder
```

(Not sure which option needed to be specified exactly, but that's just a pointer where to look).

As for rust-tls-api, I think maybe this option should be specified when `set_verify_hostname` is called. Don't know for sure.

**Comment by cecton** [comment]
Ok thanks for your help!
