### ISSUE TITLE
why only TlsStream::get_mut

### ISSUE THREAD

**Issue by SergejJurecko** [stepancheg/rust-tls-api#6]
because there is no immutable way to get the inner stream, this prevents it being used in traits that demand immutable access. Right now you can't implement mio::Evented trait on an struct with TlsStream.

**Comment by stepancheg** [comment]
No reason. Want to create a PR?

BTW, what's your use case? Do you want to use tls_api with mio? FYI, there's an [impementation for tokio](https://github.com/stepancheg/rust-tls-api/tree/master/tokio-tls-api).

**Comment by SergejJurecko** [comment]
PR created. Yes I'm trying to use it with mio. I prefer to avoid tokio.

**Comment by SergejJurecko** [comment]
Thank you.
