### ISSUE TITLE
Mark Connector/Acceptor tuple members as public

### ISSUE THREAD

**Issue by stuartnelson3** [stepancheg/rust-tls-api#9]
It would offer more flexibility when creating these structs if we weren't forced to use a pkcs12 file. How do you feel about making these public, so that a user can bring his/her own connection to the party and then be able to use the rest of the crate?

For example:
https://github.com/stepancheg/rust-tls-api/blob/master/impl-openssl/src/lib.rs#L12-L16

**Comment by stepancheg** [comment]
They definitely should be accessible, but I'm not sure fields should be exposed directly.

Currently there are `underlying_mut` functions on `TlsConnectorbuilder`/`TlsAcceptorBuilder`. So probably these functions should be also on `TlsConnector` and `TlsAcceptor` traits, and probably there should be `underlying_ref` functions.

**Comment by stuartnelson3** [comment]
The issue I'm facing is that the current api for creating a `TlsAcceptorBuilder` is very inflexible -- it seems like the only way to create it is with `from_pkcs12`. In my current situation I don't have a pkcs12 archive, but rather the separate files (which end up being passed as arguments to `openssl::ssl::SslAcceptorBuilder::mozilla_intermediate` anyway).

The `underlying_mut` on `TlsAcceptorBuilder` is only available after I've already created the struct using `from_pkcs12`.

Maybe not making the field public, but maybe allowing to set the field on creation?

**Comment by stepancheg** [comment]
I've made fields public in c06ce434c89a3b985e1b84a29a80669bbd21fb95. Thank you for the feedback!
